name: Update Keywords

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update-keywords:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Run update script
      run: node update-keywords.js

    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PAT }} # 여기서 'GH_PAT'는 시크릿의 이름
      run: |
        git config --local user.email "dubi8205@gmail.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Auto-update keyword data"
        git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/db517/keyword-tracking

